import * as React from "react";
import {
    Html,
    Head,
    Preview,
    Body,
    Container,
    Heading,
    Text,
    Button,
    Hr,
    Section,
} from "@react-email/components";
import Link from "next/link";

interface IJobApplicationEmailTemplateProps {
    applicantName: string;
    applicantEmail: string;
    phoneNumber: string;
    job: string;
    message?: string;
}

export const JobApplicationEmailTemplate = ({
    applicantName,
    applicantEmail,
    phoneNumber,
    job,
    message,
}: IJobApplicationEmailTemplateProps) => {
    return (
        <Html>
            <Head />
            <Preview>New Application Received from {applicantName}</Preview>
            <Body
                style={{
                    backgroundColor: "#f4f8ff",
                    padding: "20px",
                    fontFamily: "Arial, sans-serif",
                }}
            >
                <Container
                    style={{
                        backgroundColor: "#ffffff",
                        padding: "20px",
                        borderRadius: "8px",
                        boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
                    }}
                >
                    <Heading
                        style={{
                            color: "#007BFF",
                            textAlign: "center",
                            fontSize: "24px",
                            marginBottom: "10px",
                        }}
                    >
                        📩 New Application Submitted
                    </Heading>

                    <Text style={{ color: "#333", fontSize: "16px", lineHeight: "1.5" }}>
                        A new application has been submitted on your website.
                    </Text>

                    <Section
                        style={{
                            marginTop: "20px",
                            padding: "10px",
                            backgroundColor: "#f4f8ff",
                            borderRadius: "5px",
                        }}
                    >
                        <Text style={{ fontSize: "16px", fontWeight: "bold", color: "#007BFF" }}>
                            Applicant Details:
                        </Text>
                        <Text style={{ color: "#333", fontSize: "16px" }}>
                            <strong>Name:</strong> {applicantName} <br />
                            <strong>Email:</strong> {applicantEmail} <br />
                            <strong>Phone:</strong> {phoneNumber} <br />
                            <strong>Job Opening:</strong> {job}
                        </Text>

                        {message && (
                            <>
                                <Text
                                    style={{
                                        fontSize: "16px",
                                        fontWeight: "bold",
                                        color: "#007BFF",
                                    }}
                                >
                                    Message:
                                </Text>
                                <Text style={{ color: "#333", fontSize: "16px" }}>{message}</Text>
                            </>
                        )}
                    </Section>

                    <Section style={{ textAlign: "center", marginTop: "20px" }}>
                        <Button
                            href={`mailto:${applicantEmail}`}
                            style={{
                                display: "inline-block",
                                backgroundColor: "#007BFF",
                                color: "#ffffff",
                                padding: "10px 20px",
                                fontSize: "16px",
                                borderRadius: "5px",
                                textDecoration: "none",
                            }}
                        >
                            Reply to Applicant
                        </Button>
                    </Section>

                    <Hr style={{ borderColor: "#ddd", marginTop: "20px" }} />

                    <Text style={{ fontSize: "14px", color: "#777", textAlign: "center" }}>
                        This email was automatically generated by <strong>Brite</strong>. If you
                        have any questions, contact us at{" "}
                        <Link
                            href="mailto:nick.walker@briteclt.com"
                            style={{ color: "#007BFF", textDecoration: "none" }}
                        >
                            nick.walker@briteclt.com
                        </Link>
                    </Text>
                </Container>
            </Body>
        </Html>
    );
};

export default JobApplicationEmailTemplate;
